defaults:
  - model: fedformer
  - trainer: local_gpu
Logging:
  level: INFO
data:
  file: ../data/raw/GAZP_10m_2002-01-01_2025-05-19.parquet
  seq_length: 60    # 10-minute bars × 60 = 10 hours
  horizon: 6         # predict 1 hour ahead
  stride: 5          # <= tweak; 1 keeps every window
mlflow:
  tracking_uri: "file:./mlruns"
  experiment_name: "stock_regression_experiments"
training:
  batch_size: 128
  learning_rate: 0.001
  num_workers: 8
  train_val_split: 0.8 # 80% for train, 20% for validation
